### ISSUE TITLE
月光下的異世界之旅 好像還沒有

### ISSUE THREAD

**Issue by sam01101** [sam01101/esjzone-mirror#3]
月光下的異世界之旅 好像還沒有
我可以把我自己爬到的放上來嗎？(html + txt)

_Originally posted by @MarcoWong1012 in https://github.com/sam01101/esjzone-mirror/discussions/1#discussioncomment-1183091_

**Comment by sam01101** [comment]
你可以直接丟到這裏我會放上去, 謝謝

**Comment by MarcoWong1012** [comment]
[月光下的異世界之旅.zip](https://github.com/sam01101/esjzone-mirror/files/6986117/default.zip)

[被勇者隊伍開除的馭獸使，邂逅了最強種的貓耳少女.zip](https://github.com/sam01101/esjzone-mirror/files/6986118/default.zip)

[被捲入了勇者召喚事件卻發現異世界很和平.zip](https://github.com/sam01101/esjzone-mirror/files/6986119/default.zip)

這三本好像都還沒有，我就放上來了，格式可能跟你爬的不一樣，請見諒

**Comment by MarcoWong1012** [comment]
[轉生貴族的異世界冒險錄web.zip](https://github.com/sam01101/esjzone-mirror/files/6986132/web.zip)

再補一本

**Comment by MarcoWong1012** [comment]
[瓦爾哈拉·神槍館.zip](https://github.com/sam01101/esjzone-mirror/files/6986161/default.zip)

抱歉再補

**Comment by sam01101** [comment]
等待編譯結果

**Comment by sam01101** [comment]
應該都有了
